version: '3.8'

services:
  db-dev:
    image: postgres:13.1
    container_name: clina-db-dev
    restart: always
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    environment:
      POSTGRES_USER: clina-dev
      POSTGRES_PASSWORD: v4v7dwJyA4tL7STV
      POSTGRES_DB: clina_db
    volumes:
      - ./db_dev:/var/lib/postgresql/data
    ports:
      - '5432:5432'
